declare module 'slash2';
declare module '*.css';
declare module '*.less';
declare module '*.scss';
declare module '*.sass';
declare module '*.svg';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.bmp';
declare module '*.tiff';
declare module 'omit.js';
declare module 'numeral';
declare module '@antv/data-set';
declare module 'mockjs';
declare module 'react-fittext';
declare module 'bizcharts-plugin-slider';
declare module 'ws';
declare module 'sockjs-client';
declare module 'dva-core';
declare module 'dva-loading';
declare module '@umijs/plugin-model';

declare const REACT_APP_ENV: 'test' | 'dev' | 'pre' | false;
